### ISSUE TITLE
Undeclared dependency on cpphs

### ISSUE THREAD

**Issue by peti** [agocorona/MFlow#63]
MFlow needs cpphs to compile, but that dependency is not declared in the Cabal file. This causes build failures on NixOS and probably on other distributions, too.

**Comment by agocorona** [comment]
Hi Peter,
Do you mean the last version 0.4.5.10?

It does not depend on cpphs. That dependency is in one of the examples and
cpphs is not a library but an executable preprocessor, so cabal can not
express such dependency.

It was required in some previous version of MFlow to compile the examples,
but for that reason the examples were suppressed from the installation
process in latest versions.

2015-08-29 20:01 GMT+02:00 Peter Simons <notifications@github.com>:

> MFlow needs cpphs to compile, but that dependency is not declared in the
> Cabal file. This causes build failures on NixOS and probably on other
> distributions, too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agocorona/MFlow/issues/63>.
>



-- 
Alberto.

**Comment by peti** [comment]
Yes, I mean version 0.4.5.10.

> It does not depend on cpphs. That dependency is in one of the examples and cpphs is not a library but an executable preprocessor, so cabal can not express such dependency.

Huh? Of course it can! Isn't that exactly what the `build-tool` stanza is for?

**Comment by agocorona** [comment]
Ok,
I mxed cpphs with monadloc_pp, which is the preprocessor that need he
examples.

How to use build_tool? I find no documentation about it . looking at
https://github.com/haskell/cabal/issues/1466 I think that it needs a line
somewhere in the cabal file like;

build_tool: cpphsProgram

But I don't know

2015-08-29 22:30 GMT+02:00 Peter Simons <notifications@github.com>:

> Yes, I mean version 0.4.5.10.
>
> It does not depend on cpphs. That dependency is in one of the examples and
> cpphs is not a library but an executable preprocessor, so cabal can not
> express such dependency.
>
> Huh? Of course it can! Isn't that exactly what the build-tool stanza is
> for?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agocorona/MFlow/issues/63#issuecomment-136045669>.
>



-- 
Alberto.

**Comment by peti** [comment]
https://www.haskell.org/cabal/users-guide/developing-packages.html describes the `build-tools:` stanza.

**Comment by agocorona** [comment]
Uploaded 0.4.5.11



2015-08-30 1:02 GMT+02:00 Peter Simons <notifications@github.com>:

> https://www.haskell.org/cabal/users-guide/developing-packages.html
> describes the build-tools: stanza.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agocorona/MFlow/issues/63#issuecomment-136059246>.
>



-- 
Alberto.

**Comment by peti** [comment]
Thank you for the quick fix!

**Comment by agocorona** [comment]
Thank you for the interest in MFlow!

2015-08-30 2:11 GMT+02:00 Peter Simons <notifications@github.com>:

> Thank you for the quick fix!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agocorona/MFlow/issues/63#issuecomment-136064958>.
>



-- 
Alberto.

**Comment by peti** [comment]
Why has the declaration of the `build-tools: cpphs` dependency vanished again from 0.4.5.11's Cabal file? Now we're back to the same build error that was already fixed before. :disappointed:

**Comment by geraldus** [comment]
Hmm... I can't be certain, but I have never used (and even installed) `cpphs` on my OS X laptop, but my current `MFlow` projects compile just fine with `stack` tool.

**Comment by agocorona** [comment]
It was due to a bad synchronization. Fixing it to drop cpphs as a
dependency. Sorry

2015-09-21 7:34 GMT+02:00, Peter Simons <notifications@github.com>:
> Why has the declaration of the `build-tools: cpphs` dependency vanished
> again from 0.4.5.11's Cabal file? Now we're back to the same build error
> that was already fixed before. :disappointed:
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/agocorona/MFlow/issues/63#issuecomment-141880870


-- 
Alberto.

**Comment by agocorona** [comment]
uploading 4.6.0

2015-09-21 11:18 GMT+02:00, Alberto G. Corona <agocorona@gmail.com>:
> It was due to a bad synchronization. Fixing it to drop cpphs as a
> dependency. Sorry
>
> 2015-09-21 7:34 GMT+02:00, Peter Simons <notifications@github.com>:
>> Why has the declaration of the `build-tools: cpphs` dependency vanished
>> again from 0.4.5.11's Cabal file? Now we're back to the same build error
>> that was already fixed before. :disappointed:
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/agocorona/MFlow/issues/63#issuecomment-141880870
>
>
> --
> Alberto.
>


-- 
Alberto.
